server:
    bind:
        host: 0.0.0.0
        port: 5000
    url: https://api.ogc.met.no
    mimetype: application/json; charset=UTF-8
    encoding: utf-8
    gzip: false
    languages:
        # First language is the default language
        - en-US
    pretty_print: true
    limit: 10
    map:
        url: https://tile.openstreetmap.org/{z}/{x}/{y}.png
        attribution: '&copy; <a href="https://openstreetmap.org/copyright">OpenStreetMap contributors</a>'

logging:
    level: ERROR

metadata:
    identification:
        title:
            en: NBS NetCDF On-Demand API
        description:
            en: NBS provides an API for serving CF-NetCDF files for Sentinel products
        keywords:
            en:
                - sentinel
                - data
                - api
        keywords_type: theme
        terms_of_service: https://sentinels.copernicus.eu/documents/247904/690755/Sentinel_Data_Legal_Notice
        url: https://www.satellittdata.no
    license:
        name: Sentinel_Data_Legal_Notice
        url: https://sentinels.copernicus.eu/documents/247904/690755/Sentinel_Data_Legal_Notice
    provider:
        name: Norwegian National Ground Segment for Satellite Data
        url: https://www.satellittdata.no
    contact:
        name: NBS Helpdesk
        address: Norwegian Meteorological Institute, Henrik Mohns plass 1
        city: Oslo
        postalcode: '0313'
        country: Norway
        email: nbs-helpdesk@met.no
        url: https://www.satellittdata.no/
        role: pointOfContact

resources:
    safe-to-netcdf:
        type: process
        processor:
            name: SafeToNetCDF
